### ISSUE TITLE
docker hub no arm version

### ISSUE THREAD

**Issue by owen200008** [oceanbase/ob-operator#90]
### Description

docker hub no arm version

**Comment by chris-sun-star** [comment]
Thank you for your suggestion, we're now developing and testing the project mainly based on x86 platform, if you have this requirement, we may publish an arm version image in next release, it will come in this month

**Comment by chris-sun-star** [comment]
If you'd like to use the arm image now, you can still try to build it from the code
0. checkout the code from 2.0.x_dev branch
1. modify the Dockerfile, change base image from  openanolis/anolisos:8.4-x86_64 to openanolis/anolisos:8.8 since 8.8 provides both x86 and arm version, and do not need to specify it in tag, or any other arm version base image if you'd like to
2. delete the  GOARCH=amd64 in build command in Dockerfile
3. build docker image using the following command, make docker-build
we'll really appreciate if you create a PR if you successfully build the image and use it in K8s

**Comment by chris-sun-star** [comment]
and related images, you can found the images here
1. ob-operator:  https://hub.docker.com/r/oceanbase/ob-operator/tags
2. oceanbase-cloud-native: https://hub.docker.com/r/oceanbase/oceanbase-cloud-native/tags
3. obproxy-ce: https://hub.docker.com/repository/docker/oceanbase/obproxy-ce/tags
4. obagent: https://hub.docker.com/r/oceanbase/obagent/tags
5. ob-configserver: https://hub.docker.com/r/oceanbase/ob-configserver/tags
