### ISSUE TITLE
[Question]: observer启动命令中能否只使用local_ip不使用devname

### ISSUE THREAD

**Issue by uroot666** [oceanbase/ob-operator#93]
### Description

ob-operator：2.0
我们的环境没办法使用calico来支持IP保持不变，并且要考虑在k8s整体挂掉的情况下还能使用数据目录还原数据，所以尝试在使用Hostnetwork模式
```
func (m *OBServerManager) SupportStaticIp() bool {
	if obcluster.Spec.HostNetwork {
		m.Logger.Info("current network is HostNetwork")
		return true
	}
```
目前有个问题就是observer启动命令中写死了网卡名称为eth0，在多网卡并且没有eth0的情况下服务启动会有问题
cmd := fmt.Sprintf("cd %s && %s/bin/observer --nodaemon --appname %s --cluster_id %s --zone %s --devname %s
将devname修改为local_ip的方式是否会影响operater的其它功能

**Comment by chris-sun-star** [comment]
Using local_ip  requires observer version >= 4.2.0, and the code in oceanbase-helper is designed for all version >= 4.0, If you'd like to change the startup command, it's ok to modify the code and build an image by yourself, it won't affect other functions of ob-operator
But there's still a problem, in current implementation, ob-operator will determine cni by annotation, currently it only supports calico, for other cni and hostnetwork, ob-operator will create new pod instead of using the old one, so it still need to test carefully

**Comment by uroot666** [comment]
目前测试使用的是4.2.0，改成local_ip之后目前测试的是可行。另外我是尝试加上了hostnetwork的配置，暂时测试也是可行的。

**Comment by chris-sun-star** [comment]
That's great, would you like to create a PR, and we can test hostnetwork mode

**Comment by chris-sun-star** [comment]
We've implemented a new way to maintain observer ip address, by creating a service for each observer pod and pass the address through command line parameter, observer will use this address to communicate with each other, this feature will come with oceanbase version 4.2.3, service is a native resource of kubernetes, so we can drop the dependency of certain CNI, this feature will come with our next release 2.2.0
